### ISSUE TITLE
Modificació del valor de referencia "Vall-de-Roures"

### ISSUE THREAD

**Issue by atarom** [OSM-Catalan/monitorOSM#6]
Segons tot lo comentat a
https://t.me/osmcat/50712
el valor de referència ha de ser "Vall-de-roures" en lloc de "Vall-de-Roures"

https://esadir.cat/Toponims/Paisos_Catalans/Franja_de_Ponent/Matarranya/Vall-de-roures

**Comment by jmaspons** [comment]
Ok! I el `name` el deixo amb la forma oficial, oi?
